package factory

import (
	"context"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"regexp"
	"strings"
	"unicode/utf8"
)

// Limits on what one job may publish.
const (
	MaxFiles     = 500
	MaxTotalSize = 5 << 20
	maxBody      = 8 << 20
	maxTitle     = 200
	maxPRBody    = 60000
)

var (
	agentName = regexp.MustCompile(`^[a-z][a-z0-9-]{1,38}[a-z0-9]$`)
	jobID     = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,39}$`)
	commitSHA = regexp.MustCompile(`^[0-9a-f]{40}$`)
)

// File is one file of the new agent, relative to the repository root.
type File struct {
	Path       string `json:"path"`
	Content    []byte `json:"content"` // base64 in JSON
	Executable bool   `json:"executable,omitempty"`
}

// PRRequest asks for a branch and a pull request that add one agent.
type PRRequest struct {
	Job   string `json:"job"`
	Agent string `json:"agent"`
	// Base is the commit the factory checked out; the branch is built on it.
	Base  string `json:"base"`
	Title string `json:"title"`
	Body  string `json:"body"`
	Files []File `json:"files"`
}

// Check enforces the factory's authority: new files under agents/<agent>/
// only, within size limits. It is the publisher's own check; nothing the
// factory says is trusted.
func (r *PRRequest) Check() error {
	if !agentName.MatchString(r.Agent) {
		return fmt.Errorf("invalid agent name %q", r.Agent)
	}
	if !jobID.MatchString(r.Job) {
		return fmt.Errorf("invalid job id %q", r.Job)
	}
	if !commitSHA.MatchString(r.Base) {
		return fmt.Errorf("base must be a full commit sha")
	}
	if r.Title == "" || len(r.Title) > maxTitle || strings.ContainsAny(r.Title, "\r\n") {
		return fmt.Errorf("title must be one line of at most %d bytes", maxTitle)
	}
	if len(r.Body) > maxPRBody || !utf8.ValidString(r.Body) {
		return fmt.Errorf("body must be valid UTF-8 of at most %d bytes", maxPRBody)
	}
	if len(r.Files) == 0 || len(r.Files) > MaxFiles {
		return fmt.Errorf("want 1..%d files, got %d", MaxFiles, len(r.Files))
	}
	prefix := "agents/" + r.Agent + "/"
	seen := map[string]bool{}
	total := 0
	for _, f := range r.Files {
		if err := checkPath(f.Path, prefix); err != nil {
			return err
		}
		if seen[f.Path] {
			return fmt.Errorf("duplicate path %s", f.Path)
		}
		seen[f.Path] = true
		total += len(f.Content)
	}
	if total > MaxTotalSize {
		return fmt.Errorf("files total %d bytes, limit %d", total, MaxTotalSize)
	}
	if !seen[prefix+"agent.yaml"] {
		return fmt.Errorf("missing %sagent.yaml", prefix)
	}
	return nil
}

func checkPath(p, prefix string) error {
	switch {
	case !strings.HasPrefix(p, prefix) || len(p) == len(prefix):
		return fmt.Errorf("%q is outside %s", p, prefix)
	case path.Clean(p) != p, strings.ContainsAny(p, "\\\x00"), !utf8.ValidString(p):
		return fmt.Errorf("%q is not a clean path", p)
	}
	for _, part := range strings.Split(p, "/") {
		if part == ".." || part == "." || part == ".git" {
			return fmt.Errorf("%q has a forbidden component", p)
		}
	}
	return nil
}

// Branch is the branch a request publishes to.
func (r *PRRequest) Branch() string { return "factory/" + r.Agent + "-" + r.Job }

// Publisher opens pull requests against one base branch.
type Publisher struct {
	GitHub *GitHub
	Base   string // main
	Label  string // applied to every PR; "" for none
	Logger *slog.Logger
}

// ErrExists means the agent already exists on the base branch.
var ErrExists = errors.New("agent already exists")

// Publish creates the branch and the PR. The new agent's directory must not
// exist on the base branch: the factory creates agents, it does not edit them.
func (p *Publisher) Publish(ctx context.Context, r PRRequest) (PullRequest, error) {
	if err := r.Check(); err != nil {
		return PullRequest{}, err
	}
	dir := "agents/" + r.Agent
	for _, ref := range []string{p.Base, r.Base} {
		exists, err := p.GitHub.Exists(ctx, dir, ref)
		if err != nil {
			return PullRequest{}, err
		}
		if exists {
			return PullRequest{}, fmt.Errorf("%w: %s at %s", ErrExists, dir, ref)
		}
	}
	tree, err := p.GitHub.commitTree(ctx, r.Base)
	if err != nil {
		return PullRequest{}, fmt.Errorf("base commit: %w", err)
	}
	entries := make([]treeEntry, 0, len(r.Files))
	for _, f := range r.Files {
		sha, err := p.GitHub.createBlob(ctx, f.Content)
		if err != nil {
			return PullRequest{}, fmt.Errorf("blob %s: %w", f.Path, err)
		}
		mode := "100644"
		if f.Executable {
			mode = "100755"
		}
		entries = append(entries, treeEntry{Path: f.Path, Mode: mode, Type: "blob", SHA: sha})
	}
	newTree, err := p.GitHub.createTree(ctx, tree, entries)
	if err != nil {
		return PullRequest{}, fmt.Errorf("tree: %w", err)
	}
	commit, err := p.GitHub.createCommit(ctx, fmt.Sprintf("Add %s\n\nGenerated by tap-factory job %s.", r.Agent, r.Job), newTree, r.Base)
	if err != nil {
		return PullRequest{}, fmt.Errorf("commit: %w", err)
	}
	if err := p.GitHub.createRef(ctx, r.Branch(), commit); err != nil {
		return PullRequest{}, fmt.Errorf("branch %s: %w", r.Branch(), err)
	}
	pr, err := p.GitHub.createPR(ctx, r.Title, r.Body, r.Branch(), p.Base)
	if err != nil {
		return PullRequest{}, fmt.Errorf("pull request: %w", err)
	}
	if p.Label != "" {
		if err := p.GitHub.addLabels(ctx, pr.Number, p.Label); err != nil {
			p.Logger.Warn("label failed", "pr", pr.Number, "err", err)
		}
	}
	return pr, nil
}

// Handler serves the publisher's loopback API. Every call except /healthz
// needs the shared bearer token.
//
//	GET  /v1/head  -> {"sha": "<base branch head>"}
//	POST /v1/pr    PRRequest -> PullRequest
func Handler(p *Publisher, token string) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	auth := func(next http.HandlerFunc) http.HandlerFunc {
		return func(w http.ResponseWriter, req *http.Request) {
			got, _ := strings.CutPrefix(req.Header.Get("Authorization"), "Bearer ")
			if token == "" || subtle.ConstantTimeCompare([]byte(got), []byte(token)) != 1 {
				http.Error(w, "unauthorized", http.StatusUnauthorized)
				return
			}
			next(w, req)
		}
	}
	mux.HandleFunc("GET /v1/head", auth(func(w http.ResponseWriter, req *http.Request) {
		sha, err := p.GitHub.BranchSHA(req.Context(), p.Base)
		if err != nil {
			p.Logger.Error("head failed", "err", err)
			http.Error(w, err.Error(), http.StatusBadGateway)
			return
		}
		writeJSON(w, http.StatusOK, map[string]string{"sha": sha, "branch": p.Base})
	}))
	mux.HandleFunc("POST /v1/pr", auth(func(w http.ResponseWriter, req *http.Request) {
		var r PRRequest
		dec := json.NewDecoder(http.MaxBytesReader(w, req.Body, maxBody))
		dec.DisallowUnknownFields()
		if err := dec.Decode(&r); err != nil {
			http.Error(w, "bad request: "+err.Error(), http.StatusBadRequest)
			return
		}
		log := p.Logger.With("event", "publish", "job", r.Job, "agent", r.Agent, "base", r.Base, "files", len(r.Files))
		if err := r.Check(); err != nil {
			log.Warn("refused", "reason", err.Error())
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		pr, err := p.Publish(req.Context(), r)
		switch {
		case errors.Is(err, ErrExists):
			log.Warn("refused", "reason", err.Error())
			http.Error(w, err.Error(), http.StatusConflict)
		case err != nil:
			log.Error("failed", "err", err)
			http.Error(w, err.Error(), http.StatusBadGateway)
		default:
			log.Info("opened", "pr", pr.Number, "url", pr.URL, "branch", r.Branch())
			writeJSON(w, http.StatusOK, pr)
		}
	}))
	return mux
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func b64std(b []byte) string { return base64.StdEncoding.EncodeToString(b) }
